name: CI

on: [ push ]
jobs:
  ci:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - run: pylint --max-line-length=120 netbox_pve_sync